resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

service:
  type: NodePort

ingress:
  enabled: false

mariadb:
  primary:
    resources:
      requests:
        cpu: 250m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi

wordpress:
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    storageClassName: "standard"
    size: "1Gi"
  podLabels:
    app: wordpress
    tier: frontend
    environment: test